"""sync drive options: captions toggle, index workers

Revision ID: 00efe0293465
Revises: 1c175e28cab5
Create Date: 2026-08-19 00:09:22.674775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00efe0293465'
down_revision = '1c175e28cab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captions_enabled', sa.Boolean(),
                                      nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('index_workers', sa.Integer(),
                                      nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.drop_column('index_workers')
        batch_op.drop_column('captions_enabled')

    # ### end Alembic commands ###
