"""synced drives

Revision ID: 14b7197e2390
Revises: 9f4dbb9d4221
Create Date: 2026-08-18 01:03:12.839009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b7197e2390'
down_revision = '9f4dbb9d4221'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_column('source_path')

    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('source_path')

    # ### end Alembic commands ###
