"""drive last sync stats

Revision ID: 1c175e28cab5
Revises: 14b7197e2390
Create Date: 2026-08-18 23:29:40.979925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c175e28cab5'
down_revision = '14b7197e2390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_sync_stats', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drives', schema=None) as batch_op:
        batch_op.drop_column('last_sync_stats')

    # ### end Alembic commands ###
