"""ai connection rate limit

Revision ID: 34b417e8a07b
Revises: cbacbe527dda
Create Date: 2026-08-17 18:20:28.380126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b417e8a07b'
down_revision = 'cbacbe527dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_limit_rpm', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_connections', schema=None) as batch_op:
        batch_op.drop_column('rate_limit_rpm')

    # ### end Alembic commands ###
