"""ai connections

Revision ID: 3afab4cdb2a7
Revises: 068c55433ef8
Create Date: 2026-08-14 16:52:21.665974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3afab4cdb2a7'
down_revision = '068c55433ef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('vision_model', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_connections_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_connections_user_id'))

    op.drop_table('ai_connections')
    # ### end Alembic commands ###
