"""file trash (deleted_at)

Revision ID: 9f4dbb9d4221
Revises: 34b417e8a07b
Create Date: 2026-08-17 23:59:55.681294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4dbb9d4221'
down_revision = '34b417e8a07b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_files_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_deleted_at'))
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
