"""file versions

Revision ID: cbacbe527dda
Revises: 43d0475ce6e2
Create Date: 2026-08-15 21:16:56.194529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbacbe527dda'
down_revision = '43d0475ce6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('stored_name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_versions_file_id'), ['file_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_versions_file_id'))

    op.drop_table('file_versions')
    # ### end Alembic commands ###
